name: Auto Release

on:
  push:
    branches: [ main ]
    paths:
      - 'package.json'

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      version-changed: ${{ steps.check.outputs.changed }}
      new-version: ${{ steps.check.outputs.version }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
        
    - name: Check if version changed
      id: check
      run: |
        # Get current version
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        
        # Get previous version
        git checkout HEAD~1 package.json
        PREVIOUS_VERSION=$(node -p "require('./package.json').version")
        git checkout HEAD package.json
        
        echo "Current version: $CURRENT_VERSION"
        echo "Previous version: $PREVIOUS_VERSION"
        
        if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "Version changed from $PREVIOUS_VERSION to $CURRENT_VERSION"
        else
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No version change detected"
        fi

  check-tag-exists:
    runs-on: ubuntu-latest
    needs: check-version
    if: needs.check-version.outputs.version-changed == 'true'
    outputs:
      tag-exists: ${{ steps.check-tag.outputs.exists }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Check if tag already exists
      id: check-tag
      run: |
        VERSION="${{ needs.check-version.outputs.new-version }}"
        TAG="v$VERSION"
        
        if git rev-parse "$TAG" >/dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "Tag $TAG already exists - skipping tag creation"
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "Tag $TAG does not exist - would create tag"
        fi

  create-tag:
    runs-on: ubuntu-latest
    needs: [check-version, check-tag-exists]
    if: needs.check-version.outputs.version-changed == 'true' && needs.check-tag-exists.outputs.tag-exists == 'false'
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create and push tag
      run: |
        VERSION="${{ needs.check-version.outputs.new-version }}"
        TAG="v$VERSION"
        
        # Configure git
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # Create tag
        git tag -a "$TAG" -m "Release $VERSION"
        git push origin "$TAG"
        
        echo "Created and pushed tag: $TAG"